# Generated by Django 2.2 on 2019-04-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poonjeeMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('account_desc', models.CharField(blank=True, max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=22)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=200)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=22)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=22)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('barcode', models.CharField(max_length=150)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=22)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=22)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_desc', models.CharField(max_length=50)),
                ('seller_address', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='poonjee_users',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Sales_Transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale_type', models.CharField(max_length=15)),
                ('transaction_amt', models.DecimalField(decimal_places=2, max_digits=22)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('account_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Accounts_Info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Poonjee_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Transactions',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('transaction_amt', models.DecimalField(decimal_places=2, max_digits=22)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('account_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Accounts_Info')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Seller_Info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Poonjee_Users')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Shelf_Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_in_date', models.DateTimeField(blank=True)),
                ('latest_out_date', models.DateTimeField(blank=True)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty', models.IntegerField()),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Products')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Inventories')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Purchase_Transactions')),
            ],
        ),
        migrations.AddField(
            model_name='accounts_info',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poonjeeMain.Poonjee_Users'),
        ),
    ]
